import { PrismaClient, Mode, Difficulty } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import { Pool } from "pg"

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || "postgres://postgres:postgres@localhost:51214/template1?sslmode=disable",
})
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter } as any)

async function main() {
  console.log("Seeding ClauseRank database...")

  // Tracks
  const tracks = await Promise.all([
    prisma.track.upsert({
      where: { slug: "legal-engineering" },
      update: {},
      create: {
        name: "Legal Engineering",
        slug: "legal-engineering",
        description: "Translate legal requirements into structured logic, contract automation, state machines, and obligation workflows.",
        isPremium: false,
        icon: "⚖️",
      },
    }),
    prisma.track.upsert({
      where: { slug: "compliance-risk" },
      update: {},
      create: {
        name: "Compliance & Risk",
        slug: "compliance-risk",
        description: "AML, KYC, sanctions screening, governance controls, and regulatory workflow design.",
        isPremium: false,
        icon: "🛡️",
      },
    }),
    prisma.track.upsert({
      where: { slug: "ai-assisted-legal" },
      update: {},
      create: {
        name: "AI-Assisted Legal Work",
        slug: "ai-assisted-legal",
        description: "Review, repair, and improve AI-generated legal clauses and compliance workflows.",
        isPremium: false,
        icon: "🤖",
      },
    }),
    prisma.track.upsert({
      where: { slug: "xrpl-payments" },
      update: {},
      create: {
        name: "XRPL Payments",
        slug: "xrpl-payments",
        description: "Payment flows, remittances, and settlement logic on the XRP Ledger.",
        isPremium: false,
        icon: "💸",
        isXrplTrack: true,
      },
    }),
    prisma.track.upsert({
      where: { slug: "xrpl-escrow" },
      update: {},
      create: {
        name: "XRPL Escrow",
        slug: "xrpl-escrow",
        description: "Conditional payment release, dispute windows, and expiry logic using XRPL escrow primitives.",
        isPremium: false,
        icon: "🔐",
        isXrplTrack: true,
      },
    }),
    prisma.track.upsert({
      where: { slug: "xrpl-compliance" },
      update: {},
      create: {
        name: "XRPL Compliance",
        slug: "xrpl-compliance",
        description: "KYC/AML controls, sanctions screening, and regulatory conditions for XRPL-based financial flows.",
        isPremium: false,
        icon: "🏦",
        isXrplTrack: true,
      },
    }),
    prisma.track.upsert({
      where: { slug: "xrpl-tokenisation" },
      update: {},
      create: {
        name: "XRPL Tokenisation",
        slug: "xrpl-tokenisation",
        description: "Tokenised assets, trust lines, transfer restrictions, and redemption logic on the XRP Ledger.",
        isPremium: false,
        icon: "🪙",
        isXrplTrack: true,
      },
    }),
    prisma.track.upsert({
      where: { slug: "xrpl-identity" },
      update: {},
      create: {
        name: "XRPL Identity",
        slug: "xrpl-identity",
        description: "Digital identity, KYC gating, credential verification, and access control for XRPL infrastructure.",
        isPremium: false,
        icon: "🪪",
        isXrplTrack: true,
      },
    }),
  ])

  const trackMap = Object.fromEntries(tracks.map((t) => [t.slug, t.id]))

  const challenges = [
    // ─── LEGAL ENGINEERING ────────────────────────────────────────────────
    {
      title: "Build Milestone Payment Logic",
      slug: "build-milestone-payment-logic",
      trackId: trackMap["legal-engineering"],
      mode: Mode.BUILD,
      difficulty: Difficulty.BEGINNER,
      description: "Design a complete milestone payment workflow from commercial requirements.",
      scenario: `A software development company has agreed to build a custom compliance platform for a financial institution. The parties want milestone-based payments to protect both sides during delivery.\n\nThe commercial terms are:\n- 25% paid on contract signature\n- 35% paid on delivery of the working prototype\n- 40% paid on successful acceptance testing\n\nAdditional constraints:\n- Acceptance testing must be completed within 14 days of prototype delivery\n- If acceptance testing fails, the supplier has one opportunity to resubmit within 7 days\n- If the second submission also fails, the buyer may terminate and claim a partial refund of the final milestone\n- All milestone payments require written confirmation from the buyer's authorised signatory`,
      publicRequirements: {
        milestones: [
          { name: "Signature", percentage: 25, trigger: "Contract execution" },
          { name: "Prototype", percentage: 35, trigger: "Delivery confirmation" },
          { name: "Acceptance", percentage: 40, trigger: "Successful acceptance testing" },
        ],
        constraints: [
          "Acceptance testing window: 14 days from prototype delivery",
          "One resubmission permitted within 7 days of failure",
          "Termination right on second failure with partial refund",
          "Written signatory confirmation required for each milestone",
        ],
      },
      starterMaterial: null,
      visibleTests: [
        { id: "vt1", description: "All three milestones are defined with correct percentages", type: "keyword", keywords: ["25%", "35%", "40%"], weight: 10, isVisible: true },
        { id: "vt2", description: "14-day acceptance testing window is specified", type: "concept", concepts: ["14 day"], weight: 10, isVisible: true },
        { id: "vt3", description: "Resubmission right is addressed", type: "concept", concepts: ["resubmit"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "Handles acceptance failure on first attempt", type: "concept", concepts: ["fail", "resubmit"], weight: 15, isVisible: false },
        { id: "ht2", description: "Handles second acceptance failure with termination", type: "concept", concepts: ["terminat", "second"], weight: 15, isVisible: false },
        { id: "ht3", description: "Partial refund mechanism on termination is specified", type: "concept", concepts: ["refund", "partial"], weight: 15, isVisible: false },
        { id: "ht4", description: "Written authorisation requirement captured", type: "concept", concepts: ["written", "authoris"], weight: 10, isVisible: false },
        { id: "ht5", description: "7-day resubmission window is specified", type: "concept", concepts: ["7 day"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `MILESTONE PAYMENT LOGIC\n\nMilestone 1 — Contract Signature (25%)\nTrigger: Execution of agreement by both parties\nPayment: 25% of total contract value\nCondition: Authorised signatory written confirmation required\n\nMilestone 2 — Prototype Delivery (35%)\nTrigger: Supplier notifies buyer of prototype availability\nPayment: 35% of total contract value\nCondition: Written delivery confirmation from buyer's authorised signatory\nDeadline: Initiates 14-day acceptance testing window\n\nMilestone 3 — Acceptance Testing (40%)\nTrigger: Successful completion of acceptance testing\nPayment: 40% of total contract value\nCondition: Written acceptance confirmation from buyer's authorised signatory\n\nFAILURE HANDLING:\nOn first failure: Supplier may resubmit within 7 days\nOn second failure: Buyer may terminate; partial refund of milestone 3 applies\nResubmission right: One only; expires after 7 days from failure notice\n\nSTATE TRANSITIONS:\nDRAFT → SIGNED → PROTOTYPE_DELIVERED → TESTING → (ACCEPTED | FAILED_1 | FAILED_2)\nFAILED_1 → RESUBMITTED → (ACCEPTED | FAILED_2)\nFAILED_2 → TERMINATED`,
      explanation: "This challenge tests your ability to translate commercial milestone structures into precise logical conditions, including failure paths that protect both parties.",
      tags: ["milestones", "payments", "acceptance-testing", "termination"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 20,
      maxScore: 100,
    },
    {
      title: "Modify a Termination Clause",
      slug: "modify-termination-clause",
      trackId: trackMap["legal-engineering"],
      mode: Mode.MODIFY,
      difficulty: Difficulty.INTERMEDIATE,
      description: "Modify an existing termination clause to satisfy new regulatory and commercial requirements.",
      scenario: `A financial services company has an existing master services agreement with a technology vendor. Recent FCA guidance requires changes to the termination provisions for outsourcing arrangements.\n\nYou must modify the existing clause to comply with the new requirements.`,
      publicRequirements: {
        existingClause: "Either party may terminate this agreement on 30 days written notice. The company may terminate immediately on material breach.",
        newRequirements: [
          "Minimum 90-day notice period for termination by the company (regulatory requirement for outsourcing)",
          "Exit plan must be agreed before notice period begins",
          "Vendor must continue services during notice period",
          "Immediate termination right preserved only for insolvency or regulatory prohibition",
          "Data return and destruction obligations must be specified on termination",
        ],
      },
      starterMaterial: "Either party may terminate this agreement on 30 days written notice. The company may terminate immediately on material breach.",
      starterMaterialType: "contract",
      visibleTests: [
        { id: "vt1", description: "Notice period extended to 90 days", type: "concept", concepts: ["90 day"], weight: 15, isVisible: true },
        { id: "vt2", description: "Exit plan requirement is included", type: "concept", concepts: ["exit plan"], weight: 10, isVisible: true },
        { id: "vt3", description: "Service continuity during notice period addressed", type: "concept", concepts: ["continu"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "Immediate termination right limited to insolvency or regulatory prohibition", type: "concept", concepts: ["insolven"], weight: 15, isVisible: false },
        { id: "ht2", description: "Data return obligation specified on termination", type: "concept", concepts: ["data return", "data destruction", "data"], weight: 20, isVisible: false },
        { id: "ht3", description: "Exit plan must be agreed before notice period begins", type: "concept", concepts: ["before", "prior", "exit plan"], weight: 15, isVisible: false },
        { id: "ht4", description: "Regulatory prohibition included as immediate termination trigger", type: "concept", concepts: ["regulat"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `TERMINATION\n\n(a) Termination for convenience: The Company may terminate this Agreement on not less than 90 days' prior written notice to the Vendor. Notice of termination shall not take effect until the parties have agreed a written exit plan in accordance with clause (d) below.\n\n(b) Termination for cause: Either party may terminate this Agreement immediately on written notice if the other party: (i) becomes insolvent, enters administration, or makes an arrangement with creditors; or (ii) is prohibited from performing its obligations by any applicable regulatory authority.\n\n(c) Service continuity: The Vendor shall continue to perform all services throughout the notice period at no additional cost.\n\n(d) Exit plan: Prior to termination taking effect, the parties shall agree a written exit plan setting out knowledge transfer, transition assistance, and service handover steps.\n\n(e) Data obligations: On termination, the Vendor shall within 30 days: (i) return all Company data in a format specified by the Company; and (ii) destroy all copies of Company data in its possession and certify such destruction in writing.`,
      explanation: "FCA outsourcing rules (SS2/21) require enhanced termination provisions for material outsourcing arrangements, including minimum notice periods and exit planning requirements.",
      tags: ["termination", "outsourcing", "FCA", "regulatory", "data"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 25,
      maxScore: 100,
    },
    {
      title: "Design a Contract State Machine",
      slug: "design-contract-state-machine",
      trackId: trackMap["legal-engineering"],
      mode: Mode.BUILD,
      difficulty: Difficulty.INTERMEDIATE,
      description: "Build a complete state machine for a conditional payment agreement covering all valid transitions and failure states.",
      scenario: `A cross-border supply agreement requires a state machine to govern the payment and delivery lifecycle. The agreement involves a buyer (UK), a seller (Singapore), and a freight forwarder.\n\nEvents that can occur: contract_signed, goods_shipped, bill_of_lading_issued, goods_received, inspection_passed, inspection_failed, dispute_raised, dispute_resolved, payment_released, contract_terminated.\n\nYou must define: all states, valid transitions between states, conditions for each transition, and what happens on invalid transitions.`,
      publicRequirements: {
        parties: ["Buyer (UK)", "Seller (Singapore)", "Freight Forwarder"],
        events: ["contract_signed", "goods_shipped", "bill_of_lading_issued", "goods_received", "inspection_passed", "inspection_failed", "dispute_raised", "dispute_resolved", "payment_released", "contract_terminated"],
        requirements: [
          "Payment releases only after inspection passes",
          "Buyer has 72 hours after receipt to raise inspection failure",
          "One reinspection permitted after failure",
          "Dispute blocks payment release",
          "Contract can be terminated on second inspection failure",
        ],
      },
      starterMaterial: null,
      visibleTests: [
        { id: "vt1", description: "At least 5 named states defined", type: "concept", concepts: ["state", "status"], weight: 10, isVisible: true },
        { id: "vt2", description: "Payment release condition ties to inspection", type: "concept", concepts: ["inspection", "payment"], weight: 15, isVisible: true },
        { id: "vt3", description: "Dispute state blocks payment", type: "concept", concepts: ["dispute", "block"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "72-hour inspection window specified", type: "concept", concepts: ["72 hour", "72-hour"], weight: 15, isVisible: false },
        { id: "ht2", description: "Second inspection failure leads to termination", type: "concept", concepts: ["second", "terminat"], weight: 15, isVisible: false },
        { id: "ht3", description: "Invalid transitions are addressed", type: "concept", concepts: ["invalid", "not permitted", "cannot"], weight: 15, isVisible: false },
        { id: "ht4", description: "Bill of lading included as state trigger", type: "concept", concepts: ["bill of lading", "lading"], weight: 10, isVisible: false },
        { id: "ht5", description: "Dispute resolution allows payment to resume", type: "concept", concepts: ["resolv"], weight: 10, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 55 },
      modelAnswer: `CONTRACT STATE MACHINE\n\nSTATES:\nDRAFT, SIGNED, SHIPPED, IN_TRANSIT, DELIVERED, UNDER_INSPECTION, INSPECTION_PASSED, INSPECTION_FAILED, REINSPECTION, DISPUTED, PAYMENT_RELEASED, TERMINATED\n\nTRANSITIONS:\nDRAFT → SIGNED: contract_signed [both parties executed]\nSIGNED → SHIPPED: goods_shipped [seller notification]\nSHIPPED → IN_TRANSIT: bill_of_lading_issued [freight forwarder confirmation]\nIN_TRANSIT → DELIVERED: goods_received [buyer acknowledgement]\nDELIVERED → UNDER_INSPECTION: automatic [72-hour inspection window opens]\nUNDER_INSPECTION → INSPECTION_PASSED: inspection_passed [within 72 hours]\nUNDER_INSPECTION → INSPECTION_FAILED: inspection_failed [within 72 hours]\nUNDER_INSPECTION → INSPECTION_PASSED: timeout [72 hours elapsed with no failure raised]\nINSPECTION_PASSED → PAYMENT_RELEASED: payment_released [automatic]\nINSPECTION_FAILED → REINSPECTION: [one reinspection permitted]\nREINSPECTION → INSPECTION_PASSED: inspection_passed\nREINSPECTION → TERMINATED: inspection_failed [second failure]\nAny state → DISPUTED: dispute_raised [freezes payment_released transition]\nDISPUTED → [previous state]: dispute_resolved\n\nINVALID TRANSITIONS: Any attempt to trigger payment_released while in DISPUTED state is rejected. Transition from INSPECTION_FAILED directly to PAYMENT_RELEASED is not permitted.`,
      explanation: "State machines are essential for contracts with conditional payment logic. The key skill is identifying all reachable states and ensuring no valid scenario leads to an undefined state.",
      tags: ["state-machine", "supply-chain", "payment", "inspection"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 30,
      maxScore: 100,
    },

    // ─── COMPLIANCE & RISK ────────────────────────────────────────────────
    {
      title: "Build a KYC Approval Workflow",
      slug: "build-kyc-approval-workflow",
      trackId: trackMap["compliance-risk"],
      mode: Mode.BUILD,
      difficulty: Difficulty.BEGINNER,
      description: "Design a complete KYC workflow for onboarding institutional clients to a digital asset platform.",
      scenario: `A regulated digital asset exchange is onboarding institutional clients. You must design a KYC workflow that satisfies the firm's AML obligations and allows the compliance team to onboard efficiently.\n\nThe client types are: Corporate (UK), Corporate (Non-UK), High Net Worth Individual, and Politically Exposed Person (PEP).\n\nRequired checks vary by client type. All clients require identity verification and sanctions screening. Corporate clients require Ultimate Beneficial Owner (UBO) identification. PEPs require Enhanced Due Diligence (EDD) and senior management sign-off.`,
      publicRequirements: {
        clientTypes: ["Corporate UK", "Corporate Non-UK", "High Net Worth Individual", "PEP"],
        universalChecks: ["Identity verification", "Sanctions screening"],
        additionalChecks: {
          "Corporate UK": ["Companies House verification", "UBO identification (>25% ownership)", "Director verification"],
          "Corporate Non-UK": ["Equivalent company registry verification", "UBO identification", "Director verification", "Country risk assessment"],
          "PEP": ["Enhanced Due Diligence", "Source of wealth", "Senior management sign-off", "Annual review"],
        },
        escalationTriggers: ["Sanctions match", "PEP status identified", "High-risk jurisdiction", "Unusual transaction patterns during onboarding"],
      },
      starterMaterial: null,
      visibleTests: [
        { id: "vt1", description: "Identity verification included for all client types", type: "concept", concepts: ["identity verification", "identity"], weight: 10, isVisible: true },
        { id: "vt2", description: "Sanctions screening included for all client types", type: "concept", concepts: ["sanctions"], weight: 10, isVisible: true },
        { id: "vt3", description: "UBO identification required for corporate clients", type: "concept", concepts: ["ubo", "beneficial owner"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "EDD required for PEPs", type: "concept", concepts: ["enhanced due diligence", "edd"], weight: 15, isVisible: false },
        { id: "ht2", description: "Senior management sign-off for PEP clients", type: "concept", concepts: ["senior management", "sign-off", "approval"], weight: 15, isVisible: false },
        { id: "ht3", description: "Country risk assessment for non-UK corporates", type: "concept", concepts: ["country risk", "jurisdiction risk"], weight: 10, isVisible: false },
        { id: "ht4", description: "Escalation path for sanctions match", type: "concept", concepts: ["escalat", "sanctions match"], weight: 15, isVisible: false },
        { id: "ht5", description: "Annual review for PEP clients specified", type: "concept", concepts: ["annual review", "periodic review"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `KYC ONBOARDING WORKFLOW\n\nSTEP 1 — CLIENT CLASSIFICATION\nDetermine: Corporate UK / Corporate Non-UK / HNWI / PEP\nIf PEP flag triggered at any stage: escalate to EDD path\n\nSTEP 2 — UNIVERSAL CHECKS (all clients)\n- Identity verification: government-issued photo ID + proof of address\n- Sanctions screening: OFAC, UN, HMT, EU consolidated list\n- PEP screening: commercial database check\n\nSTEP 3 — CLIENT-TYPE CHECKS\nCorporate UK: Companies House verification, director verification, UBO identification (all persons owning >25%)\nCorporate Non-UK: Equivalent registry verification, director verification, UBO identification, country risk assessment\nHNWI: Source of wealth declaration, source of funds verification\nPEP: Enhanced Due Diligence, source of wealth, source of funds, senior management sign-off required\n\nSTEP 4 — ESCALATION TRIGGERS\n- Sanctions match → immediate freeze, MLRO referral\n- PEP identified → EDD required before onboarding proceeds\n- High-risk jurisdiction → Country risk assessment + compliance director approval\n- Adverse media → MLRO review\n\nSTEP 5 — APPROVAL\nStandard clients: Compliance officer approval\nPEP clients: Senior management sign-off + annual review scheduled\nRejected clients: Refusal recorded with rationale; SAR consideration`,
      explanation: "KYC workflows must be proportionate to client risk. The core skill is mapping client types to the correct due diligence requirements and building escalation paths for high-risk indicators.",
      tags: ["KYC", "AML", "due-diligence", "compliance", "PEP"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 25,
      maxScore: 100,
    },
    {
      title: "Debug a Sanctions Screening Rule",
      slug: "debug-sanctions-screening-rule",
      trackId: trackMap["compliance-risk"],
      mode: Mode.DEBUG,
      difficulty: Difficulty.INTERMEDIATE,
      description: "A sanctions screening rule has a logic flaw. Identify the failure, explain why it occurred, and produce a corrected version.",
      scenario: `A payment platform's automated sanctions screening rule was passing payments that should have been blocked. An audit found that a payment of £8,500 to a sanctioned entity was processed successfully because the entity's name appeared on the sanctions list under a slightly different spelling.\n\nThe current rule logic is producing false negatives. You must identify the flaw and fix it.`,
      publicRequirements: {
        brokenRule: {
          name: "SanctionsCheck_v1",
          logic: "IF recipient_name EXACT_MATCH sanctions_list THEN block_payment ELSE allow_payment",
          knownFailures: [
            "Transliteration variants not matched (e.g. 'Al-Qaeda' vs 'Al Qaeda')",
            "Name order variations not caught (e.g. 'John Smith' vs 'Smith, John')",
            "Aliases not checked",
            "Partial name matches not flagged for review",
          ],
        },
        requirements: [
          "Fuzzy matching with configurable threshold (recommended: 85% similarity)",
          "Alias list checking",
          "Name order normalisation",
          "Partial matches above 70% threshold sent for manual review",
          "All screening decisions must be logged with match score",
        ],
      },
      starterMaterial: "IF recipient_name EXACT_MATCH sanctions_list THEN block_payment ELSE allow_payment",
      starterMaterialType: "pseudocode",
      visibleTests: [
        { id: "vt1", description: "Exact match identified as the root flaw", type: "concept", concepts: ["exact match", "exact"], weight: 15, isVisible: true },
        { id: "vt2", description: "Fuzzy matching proposed as fix", type: "concept", concepts: ["fuzzy", "similarity"], weight: 15, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "Alias list checking included in fix", type: "concept", concepts: ["alias"], weight: 20, isVisible: false },
        { id: "ht2", description: "Name normalisation addresses order variations", type: "concept", concepts: ["normalise", "normalize", "name order"], weight: 15, isVisible: false },
        { id: "ht3", description: "Partial match threshold triggers manual review", type: "concept", concepts: ["manual review", "partial match", "70%"], weight: 20, isVisible: false },
        { id: "ht4", description: "Audit log of all screening decisions required", type: "concept", concepts: ["log", "audit"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `ROOT CAUSE:\nThe rule uses exact string matching, which fails on transliteration variants, aliases, name order differences, and typographical variations. This is a known weakness in sanctions screening that creates false negatives.\n\nCORRECTED RULE:\n\nFUNCTION screen_payment(recipient_name, amount):\n  normalised_name = normalise(recipient_name)  // lowercase, remove punctuation, standardise name order\n  \n  FOR EACH entry IN sanctions_list + alias_list:\n    normalised_entry = normalise(entry)\n    match_score = fuzzy_match(normalised_name, normalised_entry)  // e.g. Jaro-Winkler or Levenshtein\n    \n    IF match_score >= 0.85:\n      block_payment()\n      log(recipient_name, entry, match_score, "BLOCKED")\n      RETURN\n    \n    IF match_score >= 0.70:\n      flag_for_manual_review()\n      log(recipient_name, entry, match_score, "MANUAL_REVIEW")\n      RETURN\n  \n  allow_payment()\n  log(recipient_name, null, 0, "PASSED")\n\nKEY CHANGES:\n1. Fuzzy matching (≥85% = block, 70-85% = manual review)\n2. Alias list checked alongside primary list\n3. Name normalisation before comparison\n4. All decisions logged with match score for audit trail`,
      explanation: "Exact match sanctions screening is a compliance failure mode. Real systems use fuzzy matching with multiple thresholds: high confidence blocks automatically, medium confidence triggers manual review.",
      tags: ["sanctions", "AML", "fuzzy-matching", "debug", "compliance"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 20,
      maxScore: 100,
    },

    // ─── AI-ASSISTED LEGAL WORK ───────────────────────────────────────────
    {
      title: "Repair an AI-Generated Escrow Clause",
      slug: "repair-ai-escrow-clause",
      trackId: trackMap["ai-assisted-legal"],
      mode: Mode.AI_ASSISTED,
      difficulty: Difficulty.INTERMEDIATE,
      description: "An AI has generated an escrow clause with multiple errors. Identify the flaws and produce a corrected version.",
      scenario: `An AI assistant was asked to draft an escrow clause for a commercial property transaction. The output contains several errors that could create significant legal and commercial risk if used without correction.\n\nYour task is to: (1) identify each error, (2) explain why it is wrong, and (3) produce a corrected clause.`,
      publicRequirements: {
        aiOutput: `ESCROW CLAUSE (AI-Generated — contains errors)\n\n1. The Buyer shall deposit the purchase price into an escrow account within 5 business days of the agreement date.\n\n2. The escrow agent shall release funds to the Seller upon receipt of a completion notice from either party.\n\n3. If the transaction does not complete within 30 days, the escrow agent shall return all funds to the Buyer without deduction.\n\n4. The escrow agent's fees shall be paid from the escrow funds before release.\n\n5. Either party may instruct the escrow agent to release funds at any time.`,
        knownErrors: [
          "Release condition is too broad — 'either party' can trigger release",
          "No dispute mechanism if completion is contested",
          "No specification of what 'completion notice' must contain",
          "30-day return period may conflict with contractual completion date",
          "Fee deduction from escrow funds before release creates ambiguity about release amount",
          "Clause 5 directly contradicts the purpose of escrow",
        ],
      },
      starterMaterial: `ESCROW CLAUSE (AI-Generated — contains errors)\n\n1. The Buyer shall deposit the purchase price into an escrow account within 5 business days of the agreement date.\n\n2. The escrow agent shall release funds to the Seller upon receipt of a completion notice from either party.\n\n3. If the transaction does not complete within 30 days, the escrow agent shall return all funds to the Buyer without deduction.\n\n4. The escrow agent's fees shall be paid from the escrow funds before release.\n\n5. Either party may instruct the escrow agent to release funds at any time.`,
      starterMaterialType: "contract",
      visibleTests: [
        { id: "vt1", description: "Clause 2 error identified (either party release)", type: "concept", concepts: ["either party", "release condition"], weight: 15, isVisible: true },
        { id: "vt2", description: "Clause 5 error identified (unilateral release)", type: "concept", concepts: ["clause 5", "unilateral", "contradict"], weight: 15, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "Dispute mechanism added to corrected clause", type: "concept", concepts: ["dispute", "deadlock", "arbitrat"], weight: 20, isVisible: false },
        { id: "ht2", description: "Completion notice defined with required content", type: "concept", concepts: ["completion notice", "defined"], weight: 15, isVisible: false },
        { id: "ht3", description: "Refund condition tied to contractual completion date, not fixed 30-day period", type: "concept", concepts: ["completion date", "contractual"], weight: 15, isVisible: false },
        { id: "ht4", description: "Fee deduction ambiguity resolved in corrected clause", type: "concept", concepts: ["fee", "deduct", "net"], weight: 10, isVisible: false },
        { id: "ht5", description: "Requires joint instruction for release", type: "concept", concepts: ["joint", "both parties", "jointly"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `ERRORS IDENTIFIED:\n\n1. Clause 2: "either party" can trigger release — this removes the protection escrow provides. Should require joint written instruction or a defined completion trigger.\n\n2. Clause 5: Directly contradicts the purpose of escrow. Unilateral release renders the arrangement meaningless.\n\n3. No dispute mechanism: If parties disagree on whether completion occurred, there is no resolution path.\n\n4. "Completion notice" is undefined: Content, form, and who may issue it are not specified.\n\n5. 30-day longstop may conflict with the actual completion date in the purchase agreement.\n\n6. Fee deduction before release means the Seller receives less than the purchase price without knowing the net amount.\n\nCORRECTED CLAUSE:\n\n1. The Buyer shall deposit the purchase price into the Escrow Account within 5 Business Days of the Agreement Date.\n\n2. The Escrow Agent shall release the Escrow Funds to the Seller only upon receipt of a Joint Completion Notice, being a written notice signed by both parties confirming that completion of the transaction has occurred in accordance with the Purchase Agreement.\n\n3. If the Escrow Agent does not receive a Joint Completion Notice by the Longstop Date specified in the Purchase Agreement, it shall return the Escrow Funds to the Buyer within 5 Business Days, net of any fees payable under clause 4.\n\n4. The Escrow Agent's fees shall be borne equally by the parties and shall be paid separately and shall not be deducted from the Escrow Funds.\n\n5. In the event of a dispute between the parties as to whether completion has occurred, either party may refer the matter to [dispute resolution mechanism] and the Escrow Agent shall not release funds until the dispute is resolved.`,
      explanation: "AI-generated legal clauses frequently produce plausible but legally incorrect text. The critical skill is identifying structural errors — particularly conditions that negate the commercial purpose of the arrangement.",
      tags: ["AI", "escrow", "clause-repair", "property"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 25,
      maxScore: 100,
    },
    {
      title: "Improve an AI-Generated Compliance Workflow",
      slug: "improve-ai-compliance-workflow",
      trackId: trackMap["ai-assisted-legal"],
      mode: Mode.AI_ASSISTED,
      difficulty: Difficulty.ADVANCED,
      description: "An AI produced a compliance workflow for a digital asset exchange. Identify gaps, explain the risks, and produce an improved version.",
      scenario: `A digital asset exchange used an AI assistant to generate a customer onboarding compliance workflow. The workflow will be reviewed by the FCA. Your task is to identify the compliance gaps and produce an improved workflow that would satisfy UK AML regulations and the FCA's expectations for cryptoasset businesses.`,
      publicRequirements: {
        aiOutput: `Customer Onboarding Workflow (AI-Generated):\n1. Customer submits name, email, and date of birth\n2. System checks name against sanctions list\n3. If no match: account approved automatically\n4. Customer can now deposit and trade\n5. Annual review conducted by compliance team`,
        requiredStandards: ["UK Money Laundering Regulations 2017", "FCA Cryptoasset Business Registration", "JMLSG Guidance", "Travel Rule (for transfers above threshold)"],
        knownGaps: [
          "No identity document verification",
          "No proof of address",
          "No PEP screening",
          "No source of funds for high-value customers",
          "Automatic approval without human review",
          "No risk-based approach — all customers treated identically",
          "No transaction monitoring mentioned",
          "Travel Rule compliance absent",
        ],
      },
      starterMaterial: "1. Customer submits name, email, and date of birth\n2. System checks name against sanctions list\n3. If no match: account approved automatically\n4. Customer can now deposit and trade\n5. Annual review conducted by compliance team",
      starterMaterialType: "workflow",
      visibleTests: [
        { id: "vt1", description: "Identity document verification added", type: "concept", concepts: ["identity document", "passport", "photo id"], weight: 10, isVisible: true },
        { id: "vt2", description: "PEP screening added", type: "concept", concepts: ["pep", "politically exposed"], weight: 10, isVisible: true },
        { id: "vt3", description: "Automatic approval removed in favour of human review", type: "concept", concepts: ["human review", "compliance officer", "manual"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "Risk-based approach implemented (different tiers)", type: "concept", concepts: ["risk-based", "risk based", "risk tier", "low risk", "high risk"], weight: 15, isVisible: false },
        { id: "ht2", description: "Source of funds required for high-value customers", type: "concept", concepts: ["source of funds", "source of wealth"], weight: 15, isVisible: false },
        { id: "ht3", description: "Transaction monitoring referenced", type: "concept", concepts: ["transaction monitoring", "ongoing monitoring"], weight: 15, isVisible: false },
        { id: "ht4", description: "Travel Rule addressed for transfers above threshold", type: "concept", concepts: ["travel rule", "originator", "beneficiary information"], weight: 15, isVisible: false },
        { id: "ht5", description: "Proof of address required", type: "concept", concepts: ["proof of address", "address verification"], weight: 10, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 65 },
      modelAnswer: `COMPLIANCE GAPS IN AI OUTPUT:\n1. No identity document verification (fails MLR 2017 Reg 28)\n2. No proof of address\n3. No PEP screening (required by MLR 2017 Reg 35)\n4. Automatic approval creates compliance liability\n5. No risk-based differentiation (required by MLR 2017 Reg 18)\n6. No source of funds for high-value customers (EDD threshold)\n7. No ongoing transaction monitoring\n8. No Travel Rule provision\n\nIMPROVED WORKFLOW:\n\nTIER 1 — ALL CUSTOMERS:\n1. Submit: full name, date of birth, nationality, email, residential address\n2. Identity verification: government photo ID (passport / driving licence)\n3. Proof of address: utility bill or bank statement (within 3 months)\n4. Sanctions screening: OFAC, UN, HMT consolidated lists\n5. PEP screening: commercial database\n6. Compliance officer review and approval (no automatic approval)\n7. Account activation on approval\n\nTIER 2 — HIGH-RISK INDICATORS (any of: PEP, high-risk jurisdiction, deposit >£10k):\n8. Enhanced Due Diligence: source of wealth, source of funds declaration\n9. Senior compliance approval required\n10. Enhanced ongoing monitoring flag applied\n\nONGOING:\n11. Transaction monitoring: automated rules + manual review triggers\n12. Travel Rule: originator/beneficiary information required for transfers above £1,000\n13. Annual review for all customers; 6-monthly for high-risk`,
      explanation: "The FCA expects cryptoasset businesses to implement a full risk-based AML framework. Automatic approval, absent identity checks, and missing transaction monitoring are the most common regulatory failure points.",
      tags: ["AI", "compliance", "FCA", "AML", "workflow", "cryptoassets"],
      isXrplRelated: false,
      requiresXrplTestnet: false,
      estimatedMinutes: 35,
      maxScore: 100,
    },

    // ─── XRPL ESCROW ─────────────────────────────────────────────────────
    {
      title: "Build XRPL Escrow Release Logic",
      slug: "build-xrpl-escrow-release-logic",
      trackId: trackMap["xrpl-escrow"],
      mode: Mode.BUILD,
      difficulty: Difficulty.BEGINNER,
      description: "Design a complete escrow release workflow using XRPL escrow primitives. This challenge loads live data from XRPL Testnet.",
      scenario: `A fintech company wants to use the XRP Ledger's native escrow functionality to automate conditional payment release between a buyer and seller.\n\nThe legal requirements are:\n- Buyer deposits XRP into an XRPL EscrowCreate transaction\n- Funds are locked until the seller confirms delivery off-chain\n- Buyer has 48 hours after delivery confirmation to raise a dispute\n- If no dispute is raised within 48 hours, an EscrowFinish transaction may be submitted\n- If a dispute is raised, funds remain locked and a human arbitrator is notified\n- If the seller fails to deliver within 30 days, the buyer may submit an EscrowCancel after the CancelAfter time\n\nYou must design the complete workflow, including the XRPL transaction types used at each step, the off-chain conditions, and the failure handling.`,
      publicRequirements: {
        xrplTransactions: ["EscrowCreate", "EscrowFinish", "EscrowCancel"],
        offChainConditions: ["Seller delivery confirmation", "Buyer dispute (or silence = approval)", "Arbitrator resolution"],
        timeConstraints: { disputeWindow: "48 hours after delivery confirmation", expiry: "30 days for EscrowCancel eligibility" },
        liveTestnetContext: "This challenge displays a real XRPL Testnet escrow transaction for reference.",
      },
      starterMaterial: null,
      visibleTests: [
        { id: "vt1", description: "EscrowCreate used to lock funds", type: "concept", concepts: ["escrowcreate", "escrow create", "create escrow"], weight: 15, isVisible: true },
        { id: "vt2", description: "EscrowFinish used for successful release", type: "concept", concepts: ["escrowfinish", "escrow finish", "finish escrow"], weight: 15, isVisible: true },
        { id: "vt3", description: "48-hour dispute window specified", type: "concept", concepts: ["48 hour", "48-hour", "dispute window"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "EscrowCancel used for expired/disputed escrows", type: "concept", concepts: ["escrowcancel", "escrow cancel", "cancel escrow"], weight: 15, isVisible: false },
        { id: "ht2", description: "CancelAfter field addressed in escrow creation", type: "concept", concepts: ["cancelafter", "cancel after", "expir"], weight: 10, isVisible: false },
        { id: "ht3", description: "Off-chain delivery confirmation connected to on-chain release", type: "concept", concepts: ["off-chain", "off chain", "delivery confirm"], weight: 15, isVisible: false },
        { id: "ht4", description: "Dispute path prevents automatic EscrowFinish", type: "concept", concepts: ["dispute", "block", "prevent", "arbitrat"], weight: 15, isVisible: false },
        { id: "ht5", description: "Silence after dispute window treated as buyer approval", type: "concept", concepts: ["silence", "no dispute", "expir", "automatically"], weight: 10, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `XRPL ESCROW RELEASE WORKFLOW\n\nSTEP 1 — ESCROW CREATION (EscrowCreate)\nBuyer submits EscrowCreate transaction:\n- Amount: agreed XRP amount\n- Destination: seller's XRPL account address\n- CancelAfter: current Ripple epoch + 2,592,000 seconds (30 days)\n- Condition: optional cryptographic condition (PREIMAGE-SHA-256) for additional security\nResult: Funds locked on ledger; escrow object created\n\nSTEP 2 — OFF-CHAIN DELIVERY\nSeller ships goods / delivers service\nSeller submits delivery confirmation to platform (off-chain)\nPlatform records: delivery_timestamp, confirmation_id\nBuyer receives notification; 48-hour dispute window opens\n\nSTEP 3A — SUCCESSFUL RELEASE (no dispute within 48 hours)\nAfter 48-hour window expires with no dispute:\nEscrowFinish transaction submitted by platform or seller:\n- Owner: buyer's XRPL address\n- OfferSequence: sequence number of the EscrowCreate transaction\nResult: Funds released to seller\n\nSTEP 3B — DISPUTED RELEASE\nBuyer raises dispute within 48 hours:\nEscrowFinish is blocked by platform (off-chain control)\nHuman arbitrator notified\nArbitrator decision: release to seller OR cancel to buyer\nPlatform submits appropriate transaction based on decision\n\nSTEP 3C — EXPIRY REFUND (no delivery within 30 days)\nCancelAfter time reached on ledger:\nBuyer submits EscrowCancel transaction:\n- Owner: buyer's XRPL address\n- OfferSequence: sequence number of EscrowCreate\nResult: Funds returned to buyer\n\nKEY XRPL FIELDS:\n- FinishAfter: earliest time EscrowFinish can be submitted\n- CancelAfter: time after which EscrowCancel becomes valid\n- Condition/Fulfillment: cryptographic condition for additional release control`,
      explanation: "XRPL escrow uses time-based and cryptographic conditions. The critical design challenge is connecting off-chain legal conditions (delivery confirmation, dispute) to on-chain transaction eligibility.",
      tags: ["XRPL", "escrow", "EscrowCreate", "EscrowFinish", "EscrowCancel", "payments"],
      isXrplRelated: true,
      requiresXrplTestnet: true,
      xrplTxHash: null,
      estimatedMinutes: 30,
      maxScore: 100,
    },
    {
      title: "Modify XRPL Payment Compliance Controls",
      slug: "modify-xrpl-payment-compliance",
      trackId: trackMap["xrpl-compliance"],
      mode: Mode.MODIFY,
      difficulty: Difficulty.INTERMEDIATE,
      description: "Modify an existing XRPL payment workflow to add sanctions screening, jurisdiction restrictions, and audit logging.",
      scenario: `A cross-border payments firm is using XRPL for settlement between correspondent banks. Their current workflow allows any XRPL payment if both sender and recipient have completed KYC.\n\nA regulatory review has identified the following required changes:\n- Sanctions screening must occur at the time of each payment (not just at onboarding)\n- Payments to accounts in FATF high-risk jurisdictions must be blocked\n- Payments above $10,000 equivalent must require manual compliance approval before the XRPL transaction is submitted\n- All blocked or reviewed payments must be logged with reason and timestamp\n- Approved payments must include a Memo field on the XRPL transaction with a compliance reference ID`,
      publicRequirements: {
        existingWorkflow: "IF sender.kyc_status == APPROVED AND recipient.kyc_status == APPROVED THEN submit_xrpl_payment()",
        newRequirements: [
          "Real-time sanctions screening at payment time",
          "Block payments to FATF high-risk jurisdictions",
          "Manual review for payments above $10,000",
          "Audit log for all blocked and reviewed payments",
          "Compliance reference ID in XRPL Memo field",
        ],
      },
      starterMaterial: "IF sender.kyc_status == APPROVED AND recipient.kyc_status == APPROVED THEN submit_xrpl_payment()",
      starterMaterialType: "pseudocode",
      visibleTests: [
        { id: "vt1", description: "Real-time sanctions screening added", type: "concept", concepts: ["sanctions", "real-time", "payment time"], weight: 15, isVisible: true },
        { id: "vt2", description: "FATF high-risk jurisdiction block included", type: "concept", concepts: ["fatf", "high-risk jurisdiction", "jurisdiction"], weight: 15, isVisible: true },
        { id: "vt3", description: "Manual review for payments above $10,000", type: "concept", concepts: ["10,000", "$10", "manual review"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "Audit log includes reason and timestamp for blocked payments", type: "concept", concepts: ["audit log", "reason", "timestamp"], weight: 15, isVisible: false },
        { id: "ht2", description: "XRPL Memo field used for compliance reference", type: "concept", concepts: ["memo", "xrpl memo", "reference id"], weight: 20, isVisible: false },
        { id: "ht3", description: "KYC check retained from original workflow", type: "concept", concepts: ["kyc"], weight: 10, isVisible: false },
        { id: "ht4", description: "Payment blocked if sanctions match found at payment time (not just onboarding)", type: "concept", concepts: ["payment time", "each payment", "real-time"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `MODIFIED XRPL PAYMENT WORKFLOW\n\nFUNCTION process_xrpl_payment(sender, recipient, amount_usd, xrpl_amount):\n  \n  // Step 1: KYC Check (retained)\n  IF sender.kyc_status != APPROVED OR recipient.kyc_status != APPROVED:\n    block_payment(reason="KYC_INCOMPLETE")\n    audit_log(sender, recipient, amount_usd, "BLOCKED", "KYC_INCOMPLETE", timestamp())\n    RETURN\n  \n  // Step 2: Real-time Sanctions Screening\n  sender_match = sanctions_screen(sender.name, sender.address)\n  recipient_match = sanctions_screen(recipient.name, recipient.address)\n  \n  IF sender_match.score >= 0.85 OR recipient_match.score >= 0.85:\n    block_payment(reason="SANCTIONS_MATCH")\n    audit_log(sender, recipient, amount_usd, "BLOCKED", "SANCTIONS_MATCH", timestamp())\n    RETURN\n  \n  // Step 3: Jurisdiction Check\n  IF recipient.jurisdiction IN fatf_high_risk_list:\n    block_payment(reason="HIGH_RISK_JURISDICTION")\n    audit_log(sender, recipient, amount_usd, "BLOCKED", "HIGH_RISK_JURISDICTION", timestamp())\n    RETURN\n  \n  // Step 4: Threshold Review\n  compliance_ref_id = generate_ref_id()\n  \n  IF amount_usd >= 10000:\n    audit_log(sender, recipient, amount_usd, "PENDING_REVIEW", "ABOVE_THRESHOLD", timestamp())\n    approval = request_manual_review(sender, recipient, amount_usd, compliance_ref_id)\n    IF approval != APPROVED:\n      audit_log(sender, recipient, amount_usd, "BLOCKED", "REVIEW_REJECTED", timestamp())\n      RETURN\n  \n  // Step 5: Submit XRPL Payment with Memo\n  memo = { ComplianceRef: compliance_ref_id, ReviewedAt: timestamp() }\n  submit_xrpl_payment(sender.xrpl_address, recipient.xrpl_address, xrpl_amount, memo)\n  audit_log(sender, recipient, amount_usd, "PROCESSED", compliance_ref_id, timestamp())`,
      explanation: "The key changes are: real-time sanctions at payment time (not just onboarding), jurisdiction blocking, threshold-based manual review, and XRPL Memo field usage for compliance traceability.",
      tags: ["XRPL", "compliance", "sanctions", "payments", "AML", "FATF"],
      isXrplRelated: true,
      requiresXrplTestnet: false,
      estimatedMinutes: 30,
      maxScore: 100,
    },
    {
      title: "Design XRPL Token Transfer Restrictions",
      slug: "design-xrpl-token-transfer-restrictions",
      trackId: trackMap["xrpl-tokenisation"],
      mode: Mode.MODIFY,
      difficulty: Difficulty.ADVANCED,
      description: "Modify an existing tokenised bond implementation to add investor eligibility, lock-up periods, sanctions screening, and redemption logic.",
      scenario: `A UK asset manager is issuing a tokenised corporate bond on the XRPL. The bond is represented as an issued currency (IOU) via XRPL Trust Lines.\n\nThe current implementation allows any XRPL account with an established Trust Line to hold and transfer the token.\n\nNew regulatory and commercial requirements must be implemented:\n- Only FCA-authorised or institutional investors may hold the token\n- Transfers are restricted for the first 12 months from issuance (lock-up period)\n- Sanctions screening must pass before any transfer is permitted\n- The token may only be transferred to accounts that have completed the issuer's KYC process\n- Redemption must be available to all eligible holders after the maturity date\n- Jurisdiction restrictions apply: accounts in FATF high-risk jurisdictions may not hold the token`,
      publicRequirements: {
        existingImplementation: "Any XRPL account that sets a Trust Line to the issuer may hold and transfer the token",
        xrplMechanisms: ["Issued Currency (IOU)", "Trust Lines", "Offers (DEX)", "Transfer Fee", "Require Auth flag"],
        newRequirements: [
          "Investor eligibility: FCA-authorised or institutional only",
          "12-month lock-up from issuance date",
          "Sanctions screening before transfer",
          "KYC required for receiving accounts",
          "Redemption after maturity date",
          "FATF jurisdiction restriction",
        ],
      },
      starterMaterial: "Any XRPL account that sets a Trust Line to the issuer may hold and transfer the token",
      starterMaterialType: "workflow",
      visibleTests: [
        { id: "vt1", description: "Investor eligibility check included (FCA/institutional)", type: "concept", concepts: ["eligible", "fca", "institutional", "authorised"], weight: 10, isVisible: true },
        { id: "vt2", description: "12-month lock-up period specified", type: "concept", concepts: ["12 month", "lock-up", "lockup", "lock up"], weight: 10, isVisible: true },
        { id: "vt3", description: "Sanctions screening before transfer", type: "concept", concepts: ["sanctions", "screening"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "XRPL Require Auth flag used to control Trust Line establishment", type: "concept", concepts: ["require auth", "requireauth", "auth"], weight: 15, isVisible: false },
        { id: "ht2", description: "Redemption pathway specified after maturity date", type: "concept", concepts: ["redemption", "redeem", "maturity"], weight: 15, isVisible: false },
        { id: "ht3", description: "FATF jurisdiction restriction applied", type: "concept", concepts: ["fatf", "jurisdiction", "restricted"], weight: 15, isVisible: false },
        { id: "ht4", description: "KYC check required for receiving account before transfer", type: "concept", concepts: ["kyc", "receiving", "recipient"], weight: 10, isVisible: false },
        { id: "ht5", description: "Lock-up period prevents DEX trading of the token during restriction period", type: "concept", concepts: ["dex", "trading", "offer", "restrict"], weight: 15, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 65 },
      modelAnswer: `XRPL TOKENISED BOND — TRANSFER RESTRICTION IMPLEMENTATION\n\nXRPL CONFIGURATION:\n1. Issuer sets RequireAuth flag on issuing account\n   → Prevents any account from establishing a Trust Line without issuer authorisation\n   → All Trust Lines must be explicitly authorised by the issuer\n\n2. Issuer authorises Trust Lines only after off-chain verification:\n   - Investor eligibility confirmed (FCA-authorised or institutional classification)\n   - KYC completed with issuer's compliance team\n   - Jurisdiction check passed (not on FATF high-risk list)\n   - Sanctions screening cleared\n\nTRANSFER CONTROL LOGIC (off-chain, platform-enforced):\nFUNCTION approve_transfer(sender, recipient, amount, transfer_date):\n  \n  // Lock-up check\n  IF transfer_date < issuance_date + 365 days:\n    REJECT "Transfer restricted during 12-month lock-up period"\n  \n  // Recipient eligibility\n  IF NOT recipient.trust_line_authorised:\n    REJECT "Recipient does not have an authorised Trust Line"\n  \n  IF NOT recipient.kyc_complete:\n    REJECT "Recipient KYC not completed"\n  \n  // Sanctions screening\n  IF sanctions_screen(sender) OR sanctions_screen(recipient):\n    REJECT "Sanctions match — transfer blocked"\n  \n  // Jurisdiction check\n  IF recipient.jurisdiction IN fatf_high_risk_list:\n    REJECT "Jurisdiction restriction applies"\n  \n  APPROVE transfer\n\nREDEMPTION (after maturity date):\nFUNCTION process_redemption(holder, amount):\n  IF current_date < maturity_date:\n    REJECT "Bond has not yet matured"\n  IF NOT holder.trust_line_authorised:\n    REJECT "Not an eligible holder"\n  // Issuer sends fiat/cash equivalent off-chain\n  // Holder burns token by sending back to issuer account\n  submit_xrpl_payment(holder.address, issuer.address, amount)\n\nNOTE ON DEX RESTRICTION:\nDuring lock-up period, platform must ensure no Offers are created for the token on XRPL DEX. This requires either off-chain monitoring and cancellation, or use of platform-controlled accounts.`,
      explanation: "XRPL's RequireAuth flag is the key mechanism for restricting who can hold an issued currency. Transfer restrictions above that require off-chain enforcement because XRPL itself does not have programmable transfer conditions beyond basic flags.",
      tags: ["XRPL", "tokenisation", "trust-lines", "bonds", "transfer-restrictions", "RequireAuth"],
      isXrplRelated: true,
      requiresXrplTestnet: false,
      estimatedMinutes: 40,
      maxScore: 100,
    },
    {
      title: "Design XRPL Cross-Border Payment Compliance",
      slug: "design-xrpl-crossborder-payment-compliance",
      trackId: trackMap["xrpl-payments"],
      mode: Mode.BUILD,
      difficulty: Difficulty.INTERMEDIATE,
      description: "Design a compliance framework for a cross-border XRPL remittance corridor between the UK and Kenya.",
      scenario: `A fintech company is building a remittance service using the XRP Ledger as the settlement layer between a UK sending institution and a Kenyan receiving institution. The service targets migrant workers sending money home.\n\nXRP is used as a bridge currency. The corridor is: GBP (UK) → XRP (XRPL settlement) → KES (Kenya).\n\nYou must design the compliance framework covering:\n- Sender verification in the UK\n- XRPL transaction requirements\n- Recipient verification in Kenya\n- Travel Rule compliance\n- AML monitoring requirements\n- What happens when a transaction is flagged`,
      publicRequirements: {
        corridor: "GBP (UK) → XRP (XRPL) → KES (Kenya)",
        regulators: ["FCA (UK sending side)", "CBK — Central Bank of Kenya (receiving side)"],
        travelRuleThreshold: "£1,000 / equivalent",
        requirements: [
          "UK sender KYC",
          "XRPL transaction compliance fields",
          "Kenya recipient KYC (via local partner)",
          "Travel Rule: originator and beneficiary information for transactions above threshold",
          "Ongoing transaction monitoring",
          "SAR (Suspicious Activity Report) process",
        ],
      },
      starterMaterial: null,
      visibleTests: [
        { id: "vt1", description: "UK sender KYC requirements defined", type: "concept", concepts: ["sender", "kyc", "uk"], weight: 10, isVisible: true },
        { id: "vt2", description: "Travel Rule compliance addressed", type: "concept", concepts: ["travel rule", "originator", "beneficiary"], weight: 15, isVisible: true },
        { id: "vt3", description: "XRPL Memo field used for compliance data", type: "concept", concepts: ["memo", "xrpl"], weight: 10, isVisible: true },
      ],
      hiddenTests: [
        { id: "ht1", description: "£1,000 threshold specified for Travel Rule", type: "concept", concepts: ["1,000", "£1,000", "threshold"], weight: 10, isVisible: false },
        { id: "ht2", description: "Kenya recipient KYC via local partner addressed", type: "concept", concepts: ["kenya", "recipient", "local partner", "cbk"], weight: 15, isVisible: false },
        { id: "ht3", description: "SAR process defined for flagged transactions", type: "concept", concepts: ["sar", "suspicious activity", "report", "mlro"], weight: 15, isVisible: false },
        { id: "ht4", description: "Ongoing transaction monitoring specified", type: "concept", concepts: ["transaction monitoring", "ongoing monitoring"], weight: 15, isVisible: false },
        { id: "ht5", description: "XRP bridge currency role explained in compliance context", type: "concept", concepts: ["bridge", "xrp", "settlement"], weight: 10, isVisible: false },
      ],
      scoringRubric: { totalWeight: 100, passMark: 60 },
      modelAnswer: `XRPL REMITTANCE COMPLIANCE FRAMEWORK — GBP/KES CORRIDOR\n\nUK SENDER ONBOARDING (FCA-regulated):\n- Full KYC: identity document + proof of address\n- Sanctions screening: HMT + OFAC consolidated lists\n- PEP screening\n- Source of funds for transfers above £10,000\n- Ongoing monitoring: transaction pattern analysis\n\nXRPL TRANSACTION REQUIREMENTS:\n- Each XRPL payment includes a Memo field containing:\n  { originator: { name, account, reference }, beneficiary: { name, account }, compliance_ref_id, corridor: "GBP-KES" }\n- For transactions above £1,000: full Travel Rule data included in Memo or transmitted to receiving institution via secure channel (IVMS101 format)\n- Sanctions screening of both XRPL addresses before transaction submission\n\nTRAVEL RULE (above £1,000 threshold):\n- Originator information: full name, account number, address, date of birth\n- Beneficiary information: full name, account number\n- Transmitted to Kenyan receiving institution before or concurrent with XRPL settlement\n- Below £1,000: originator account reference only\n\nKENYA RECEIVING SIDE (CBK-regulated, via local partner):\n- Local partner conducts recipient KYC under CBK requirements\n- Recipient eligibility confirmed before funds disbursed in KES\n- Local partner responsible for last-mile compliance\n\nTRANSACTION MONITORING:\n- Automated rules: velocity limits, unusual amounts, dormant account activity\n- High-risk flags: transactions to high-risk jurisdictions, structuring patterns\n- Flagged transactions: held for MLRO review before XRPL submission\n\nSAR PROCESS:\n- MLRO reviews flagged transactions within 24 hours\n- Decision: proceed / block / report to NCA\n- SAR submitted to NCA if reasonable grounds for suspicion\n- Tipping off: customer not informed if SAR submitted`,
      explanation: "Cross-border XRPL payments must satisfy the regulatory requirements of both jurisdictions. The XRPL Memo field is the practical mechanism for Travel Rule compliance when carrying compliance metadata on-chain.",
      tags: ["XRPL", "payments", "remittance", "cross-border", "travel-rule", "AML", "FCA"],
      isXrplRelated: true,
      requiresXrplTestnet: false,
      estimatedMinutes: 35,
      maxScore: 100,
    },
  ]

  for (const ch of challenges) {
    await prisma.challenge.upsert({
      where: { slug: ch.slug },
      update: {},
      create: {
        ...ch,
        published: true,
      },
    })
  }

  console.log(`Seeded ${tracks.length} tracks and ${challenges.length} challenges.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
